import { library } from '@fortawesome/fontawesome-svg-core';

import { faFacebook } from '@fortawesome/free-brands-svg-icons';
import {
  faCalendarCheck as faCalendarCheckRegular,
  faUser as faUserRegular
} from '@fortawesome/free-regular-svg-icons';
import {
  faArrowTrendDown,
  faArrowTrendUp,
  faArrowsRotate,
  faBars,
  faBarsStaggered,
  faBuildingShield,
  faCalendarCheck,
  faCalendarDay,
  faCalendarDays,
  faChartPie,
  faCheck,
  faCircleExclamation,
  faCoins,
  faEllipsisVertical,
  faEnvelope,
  faFingerprint,
  faGear,
  faHouse,
  faLanguage,
  faMagnifyingGlass,
  faMoneyBillTransfer,
  faMoneyCheckDollar,
  faPen,
  faPlus,
  faPowerOff,
  faTrash,
  faUnlock,
  faUser,
  faUserSecret,
  faUsers,
  faWrench,
  faXmark
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faChartPie,
  faCoins,
  faEllipsisVertical,
  faXmark,
  faCheck,
  faCalendarCheckRegular,
  faCalendarCheck,
  faArrowsRotate,
  faCircleExclamation,
  faPlus,
  faFingerprint,
  faPen,
  faTrash,
  faUserSecret,
  faFacebook,
  faLanguage,
  faEnvelope,
  faUnlock,
  faUser,
  faUserRegular,
  faPowerOff,
  faGear,
  faHouse,
  faBars,
  faBarsStaggered,
  faArrowTrendDown,
  faArrowTrendUp,
  faMagnifyingGlass,
  faMoneyBillTransfer,
  faWrench,
  faBuildingShield,
  faUsers,
  faCalendarDay,
  faCalendarDays,
  faMoneyCheckDollar
);

export default {};
